### ISSUE TITLE
There is no license for this project

### ISSUE THREAD

**Issue by Swordancer** [brewaa/Pixabay.Net#1]
Hello,

I want to use some small part of this project in my own project and leave link to this one in the code but there is no license in readme file so I actually can't do it. I really like this project, it is very clear but without proper license we actually can't use and change source code for our own purposes. 

I would be very nice if author could update readme file with proper licence. 

More details: https://help.github.com/en/articles/licensing-a-repository

Thank you!

**Comment by brewaa** [comment]
Go for it @Swordancer ! I’ll try to get a license added but in the meantime you are welcome to use it as you see fit. Glad you like the project. Thanks for asking.

**Comment by Swordancer** [comment]
Thank you very much! :)
